# Generated by Django 5.0.7 on 2024-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comment_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
