# Generated by Django 5.0.7 on 2024-08-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caty', to='auctions.category'),
        ),
        migrations.AddField(
            model_name='listings',
            name='text',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
