# Generated by Django 5.0.7 on 2024-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_category_listings_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
