# Generated by Django 5.0.7 on 2024-08-22 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='bids',
            field=models.ManyToManyField(null=True, to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
