# Generated by Django 5.0.7 on 2024-08-25 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bids_bids_bids_listingname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listingname',
        ),
        migrations.AddField(
            model_name='bids',
            name='listingbid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingname', to='auctions.listings'),
        ),
    ]
