# Generated by Django 5.0.7 on 2024-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_category_auction_image_auction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
